### ISSUE TITLE
Verify template and layout files exist in handler

### ISSUE THREAD

**Issue by hueniverse** [hapijs/vision#10]
Otherwise, rendering fails after `onPreResponse` is called. Use response 'prepare' option.

Replaces https://github.com/hapijs/hapi/issues/1882

**Comment by jagoda** [comment]
@hueniverse you are assigned. Are you still looking at this? I may take a crack at it if you are not.

**Comment by hueniverse** [comment]
Not anymore...

**Comment by jagoda** [comment]
After looking into this, it seems to me that the full rendering process should be moved to the `prepare` step and the results stored on the source object (to be retrieved during the `marshal` step)? Otherwise other errors (like file permissions, malformed options, etc.) may not get reported until after the `onPreResponse` event as well. It seems reasonable to still set the `content-type` in the `marshal` step though. @hueniverse do you have any concerns about this approach?

**Comment by hueniverse** [comment]
The view context can change all the way until `onPreResponse`.

**Comment by jagoda** [comment]
Ah, I see. I'll see if I can come up with something better. Thanks for the tip!

**Comment by jagoda** [comment]
@hueniverse what if just the template compilation is done in the `prepare` step while the `marshal` step uses the compiled output to render the context? . Admittedly this is a bit more complicated than checking template and layout existence and means reworking the implementation a bit. However, I think it will expose a few more errors early in the request lifecycle (like file readability) without compromising the ability to modify the context object later in the lifecycle.

**Comment by hueniverse** [comment]
I'm open to it. Give it a try. Will probably need another person to do a full code review for such a major refactor.
