### ISSUE TITLE
Vue SSR Support

### ISSUE THREAD

**Issue by sustained** [hapijs/vision#154]
Looks like [Vue has SSR support now](https://ssr.vuejs.org/#what-is-server-side-rendering-ssr).

Since React SSR is supported, what are the maintainers' and contributors' thoughts on officially supporting Vue too?

**Comment by wswoodruff** [comment]
@sustained Cool! Although we do have a `jsx` example here https://github.com/hapijs/vision/tree/master/examples/jsx

hapi doesn't officially support any front-end framework -- `hapi-react-views` was used in the jsx example because it was already built, and React is popular enough.

If you'd like to see a new module be created for Vue's SSR then we can talk about a new module like [hapi-react-views](https://github.com/jedireza/hapi-react-views)

Could be `hapi-vue-views`

**Comment by sustained** [comment]
Yeah, I took a look at **hapi-react-views** the other day out of curiosity and it seems to not consist of a great deal of code so maybe this would be fairly trivial to add. Although I'm not sure I know enough about neither HAPI nor Vue myself to be the one to create it.

**Comment by wswoodruff** [comment]
Closing as this isn't an issue with Vision itself
