### ISSUE TITLE
Issue with underscore partials and vision

### ISSUE THREAD

**Issue by molekilla** [hapijs/vision#67]
Getting

```
 
Debug: internal, implementation, error 
    Error: settings.layoutKeyword conflict
...
```

with

```
module.exports = function(templ, options) {

  return function(ctx, options) {
    return require('underscore').template(templ)(ctx || null);
  };

};

module.exports = {
    engines: {
      'html': {
        compile: require('./underscore_compiler')
      }
    },
    compileMode: 'sync',
    path: __dirname + '/../../views',
    partialsPath: __dirname + '/../../views/partials'
};



```

it breaks when it tries to load the partial

similar code found here 
https://github.com/molekilla/rutha/commit/05c7b86487f5d4e0f12b5f1ce6318338c1bb746d

any idea ?

thanks

**Comment by jagoda** [comment]
The error message you mentioned typically happens when the `context` object provided has an attribute with the same name as the layout attribute. By default the layout attribute is called `content`. The layout attribute name can be configured with the [`layoutKeyword`](https://github.com/hapijs/vision/blob/master/API.md#serverviewsoptions) option. Does this help?

**Comment by molekilla** [comment]
probly ... will try

**Comment by molekilla** [comment]
fixed, closing.

**Comment by jagoda** [comment]
Glad this helped. Out of curiosity, are you using layouts at all?

**Comment by molekilla** [comment]
No, pls guide me, refactoring a huge app right now, it will be helpful.
Thanks

**Comment by jagoda** [comment]
There's some info on how to use layouts in the [hapi tutorials](http://hapijs.com/tutorials/views#layouts). There are also some code examples for layouts with handlebars in the [examples directory](https://github.com/hapijs/vision/blob/master/examples/handlebars/layout.js). I think the ideas should translate to your situation pretty well.

Since you aren't using layouts, I think I'd like to re-open this as a bug. I don't think it makes sense for a user to see a 'layoutKeyword conflict' if layouts aren't being used.
