### ISSUE TITLE
Creating a view manager in a plugin and creating routes after

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/vision#94]
I am having some troubles encapsulating the view manager in a plugin and creating routes after it has been registered.

I am encapsulating it because we have a number of applications which use a convention as to where they host their helpers/partials and thus we would like it to be easily shared code.

index.js
```javascript
    server.register(require('hapi-our-handlebars'),
    function handleHandlebars(err) {
        hoek.assert(!err, err);
        server.route({
            method: 'GET',
            path: '/my/url/{id?}',
            handler: require('./routes/myhandler')
        });
    });
```

myhandler.js
```javascript
...
request.render('our/template', {}, function handleRender(err, rendered, config) {
    return reply(rendered);
});
...
```

hapi-our-handlebars.js
```javascript
function plugin(server, options, next) {

    server.register(require('vision'), function registerViewHandler(viewHandlerError) {
        hoek.assert(!viewHandlerError, viewHandlerError);

        server.views({
            engines: {
                hbs: require('handlebars')
            },
            path: './views',
            partialsPath: ['./partials'],
            helpersPath: ['./helpers']
        });

        next();
    });
}
```

When I attempt to access this route I find an exception in my logs:

`"message":"Missing views manager"`

What am I missing? It seems like the request isn't getting render bound to it.

**Comment by devinivy** [comment]
When you use `server.views()` it sets the view manager only within the current plugin.  So there is no way to create a plugin that registers a view manager for another plugin.  However, there is one exception to that– you can set a default views manager for the entire server by using the "root server", which escapes the plugin context (in hapi this is sometimes referred to as a "realm").  To do that simply let hapi-our-handlebars.js call `server.root.views()` rather than `server.views()`.

An aside... with https://github.com/hapijs/hapi/issues/3066 (not roadmapped) what you were originally hoping to do could become possible– a plugin could reference the plugin that registered it.  This doesn't work now, but I hope some day that might look like `server.parent.views()`.

**Comment by lostthetrail** [comment]
For now, I have stopped trying to push this logic into a re-usable partial. It will remain as tech. debt for the time being. I really appreciate the help you have given @devinivy.

**Comment by devinivy** [comment]
No problem!  That helpers issue I'm not so sure about.  It could be a vision bug– not sure.  Feel free to open another issue if you can't make sense of it.
