### ISSUE TITLE
Creating a plugin which has it's own vision view handling

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/vision#98]
Hello, I am creating a re-usable error handler for a series of applications. It's job is to pick up any Boom exceptions, and log them and render a user-friendly page.

The individual applications can have different view engines and I want to provide each of these applications this solution "for free".

When I try to call request.render from it seems to be using the applications vision configuration, rather than the plugins. When I call reply.view, it seems to be using the plugins configuration, but there is a recursion possible because I don't have access to handling an error in reply.view.

Any thoughts on how to make this work or what I am missing?

error-plugin/plugin.js
```javascript
function plugin(server, options, next) {
    const safeStringify = require('json-stringify-safe');
    const hoek = require('hoek');

    server.register(require('vision'), {once: true}, function registerViewHandler(viewHandlerError) {
        hoek.assert(!viewHandlerError, viewHandlerError);

        server.views({
            engines: {
                hbs: require('handlebars')
            },
            path: './templates',
            partialsPath: ['./templates/partials/'],
            helpersPath: []
        });

        server.ext('onPreResponse', function errorHandler(request, reply) {
            const response = request.response;

            if (!response.isBoom) { return reply.continue(); }

            request.log(['error', 'exception'], `Hit the error handler: ${JSON.stringify(request.response)} - ${safeStringify(request.response.stack)}`);

            return require('./errorViewHandler')(request, reply);
        });

    });

    return next();
}
```

error-plugin/errorViewHandler.js
```javascript
function handle(request, reply) {
    const templateData = {};

    return request.render('error', templateData, function handleRender(err, rendered, config) {
        if (err) {
            request.log('error', `Rendering error page failed: ${err}`);
            return reply('An error has occured.');
        }
        return reply(rendered);
    });
}
```

**Comment by lostthetrail** [comment]
I am likely misunderstanding something about Realm in HAPI, but @hueniverse's description in #39 seems to suggest this should work.

**Comment by lostthetrail** [comment]
With a little debugging, when I get into the error-plugin's 'onPreResponse' extension point, I am back at root realm, rather than the expected error-plugin realm.

**Comment by lostthetrail** [comment]
@devinivy I noticed you were working on a [realms document](https://github.com/devinivy/hapijs.com/blob/realms-tutorial/lib/tutorials/realms.md#how-do-i-access-the-realm). Can you provide any clarity here?

**Comment by devinivy** [comment]
Sure!

When you call `request.render()` it will use the realm of the current route (the realm in which the route was defined using `server.route()`) regardless of the plugin in which your server extension was added.  Because the view manager is defined _inside_ your error-handling plugin (where `server.view()` is called), the realm of that view manager is not the same as the realm in which the route was defined.  So `request.render()` falls back to the root realm's view manager.

If you want that error-handling plugin to use its own view manager inside `onPreResponse` then you should access `render()` directly from the manager rather than on `request`.  I can expound upon that idea if it would be useful.

P.S. Advanced realming... `request` decorators typically use the realm of the current route.  The `reply` decorators, on the other hand, typically use the realm of the server extension/auth strategy/etc.  That's why `realm.view()` and `request.render()` behave differently in a server extension.  This is not well documented in the API, but it is described in my in-progress realms document!

**Comment by lostthetrail** [comment]
@devinivy As usual, thank you so much for the information. That really clears up a bunch of questions I had. This is what I ended up doing and I am glad to hear that it is the best practice.

Also, if anyone comes along afterward and views this issue. You should likely use `require('handlebars').create()` to provide your plugin with a new namespace, as to not expose your plugin to helper/partial/template registration conflicts.
